module.exports = [
    {subject_name_en:'English',subject_name_ar:'إنجليزى'},
    {subject_name_en:'Arabic',subject_name_ar:'عربى'},
    {subject_name_en:'math',subject_name_ar:'رياضيات'},
    {subject_name_en:'Science',subject_name_ar:'علوم'},
    {subject_name_en:'social studies',subject_name_ar:'دراسات'},
    {subject_name_en:'religion',subject_name_ar:'دين'},
    {subject_name_en:'french',subject_name_ar:'فرنساوى'},
    {subject_name_en:'drawing and art',subject_name_ar:'رسم'},
    {subject_name_en:'computer science',subject_name_ar:'حاسب آلى'},
    {subject_name_en:'German language',subject_name_ar:'اللغة الألمانية'},
    {subject_name_en:'chemistry',subject_name_ar:'كيمياء'},
    {subject_name_en:'physics',subject_name_ar:'فيزياء'},
    {subject_name_en:'Biology',subject_name_ar:'أحياء'},
    {subject_name_en:'geology',subject_name_ar:'جيلوجيا'},
    {subject_name_en:'philosophy',subject_name_ar:'فلسفة'},
    {subject_name_en:'psychology',subject_name_ar:'علم نفس'},
    {subject_name_en:'history',subject_name_ar:'تاريخ'},
    {subject_name_en:'Geography',subject_name_ar:'جغرافيا'},
  ];