module.exports = [
    {"governorates_of_Egypt_id":"1","city_name_ar":"15 مايو","city_name_en":"15 May"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الازبكية","city_name_en":"Al Azbakeyah"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"البساتين","city_name_en":"Al Basatin"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"التبين","city_name_en":"Tebin"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الخليفة","city_name_en":"El-Khalifa"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الدراسة","city_name_en":"El darrasa"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الدرب الاحمر","city_name_en":"Aldarb Alahmar"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الزاوية الحمراء","city_name_en":"Zawya al-Hamra"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الزيتون","city_name_en":"El-Zaytoun"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الساحل","city_name_en":"Sahel"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"السلام","city_name_en":"El Salam"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"السيدة زينب","city_name_en":"Sayeda Zeinab"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الشرابية","city_name_en":"El Sharabeya"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مدينة الشروق","city_name_en":"Shorouk"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الظاهر","city_name_en":"El Daher"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"العتبة","city_name_en":"Ataba"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"القاهرة الجديدة","city_name_en":"New Cairo"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المرج","city_name_en":"El Marg"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"عزبة النخل","city_name_en":"Ezbet el Nakhl"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المطرية","city_name_en":"Matareya"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المعادى","city_name_en":"Maadi"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المعصرة","city_name_en":"Maasara"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المقطم","city_name_en":"Mokattam"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"المنيل","city_name_en":"Manyal"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الموسكى","city_name_en":"Mosky"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"النزهة","city_name_en":"Nozha"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الوايلى","city_name_en":"Waily"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"باب الشعرية","city_name_en":"Bab al-Shereia"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"بولاق","city_name_en":"Bolaq"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"جاردن سيتى","city_name_en":"Garden City"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"حدائق القبة","city_name_en":"Hadayek El-Kobba"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"حلوان","city_name_en":"Helwan"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"دار السلام","city_name_en":"Dar Al Salam"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"شبرا","city_name_en":"Shubra"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"طره","city_name_en":"Tura"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"عابدين","city_name_en":"Abdeen"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"عباسية","city_name_en":"Abaseya"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"عين شمس","city_name_en":"Ain Shams"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مدينة نصر","city_name_en":"Nasr City"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مصر الجديدة","city_name_en":"New Heliopolis"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مصر القديمة","city_name_en":"Masr Al Qadima"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"منشية ناصر","city_name_en":"Mansheya Nasir"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مدينة بدر","city_name_en":"Badr City"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مدينة العبور","city_name_en":"Obour City"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"وسط البلد","city_name_en":"Cairo Downtown"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الزمالك","city_name_en":"Zamalek"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"قصر النيل","city_name_en":"Kasr El Nile"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الرحاب","city_name_en":"Rehab"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"القطامية","city_name_en":"Katameya"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"مدينتي","city_name_en":"Madinty"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"روض الفرج","city_name_en":"Rod Alfarag"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"شيراتون","city_name_en":"Sheraton"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الجمالية","city_name_en":"El-Gamaleya"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"العاشر من رمضان","city_name_en":"10th of Ramadan City"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"الحلمية","city_name_en":"Helmeyat Alzaytoun"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"النزهة الجديدة","city_name_en":"New Nozha"},
    {"governorates_of_Egypt_id":"1","city_name_ar":"العاصمة الإدارية","city_name_en":"Capital New"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الجيزة","city_name_en":"Giza"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"السادس من أكتوبر","city_name_en":"Sixth of October"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الشيخ زايد","city_name_en":"Cheikh Zayed"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الحوامدية","city_name_en":"Hawamdiyah"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"البدرشين","city_name_en":"Al Badrasheen"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الصف","city_name_en":"Saf"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"أطفيح","city_name_en":"Atfih"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"العياط","city_name_en":"Al Ayat"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الباويطي","city_name_en":"Al-Bawaiti"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"منشأة القناطر","city_name_en":"ManshiyetAl Qanater"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"أوسيم","city_name_en":"Oaseem"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"كرداسة","city_name_en":"Kerdasa"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"أبو النمرس","city_name_en":"Abu Nomros"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"كفر غطاطي","city_name_en":"Kafr Ghati"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"منشأة البكاري","city_name_en":"Manshiyet Al Bakari"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الدقى","city_name_en":"Dokki"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"العجوزة","city_name_en":"Agouza"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الهرم","city_name_en":"Haram"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الوراق","city_name_en":"Warraq"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"امبابة","city_name_en":"Imbaba"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"بولاق الدكرور","city_name_en":"Boulaq Dakrour"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الواحات البحرية","city_name_en":"Al Wahat Al Baharia"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"العمرانية","city_name_en":"Omraneya"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"المنيب","city_name_en":"Moneeb"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"بين السرايات","city_name_en":"Bin Alsarayat"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الكيت كات","city_name_en":"Kit Kat"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"المهندسين","city_name_en":"Mohandessin"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"فيصل","city_name_en":"Faisal"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"أبو رواش","city_name_en":"Abu Rawash"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"حدائق الأهرام","city_name_en":"Hadayek Alahram"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"الحرانية","city_name_en":"Haraneya"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"حدائق اكتوبر","city_name_en":"Hadayek October"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"صفط اللبن","city_name_en":"Saft Allaban"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"القرية الذكية","city_name_en":"Smart Village"},
    {"governorates_of_Egypt_id":"2","city_name_ar":"ارض اللواء","city_name_en":"Ard Ellwaa"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"ابو قير","city_name_en":"Abu Qir"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الابراهيمية","city_name_en":"Al Ibrahimeyah"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الأزاريطة","city_name_en":"Azarita"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الانفوشى","city_name_en":"Anfoushi"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الدخيلة","city_name_en":"Dekheila"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"السيوف","city_name_en":"El Soyof"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"العامرية","city_name_en":"Ameria"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"اللبان","city_name_en":"El Labban"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المفروزة","city_name_en":"Al Mafrouza"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المنتزه","city_name_en":"El Montaza"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المنشية","city_name_en":"Mansheya"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الناصرية","city_name_en":"Naseria"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"امبروزو","city_name_en":"Ambrozo"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"باب شرق","city_name_en":"Bab Sharq"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"برج العرب","city_name_en":"Bourj Alarab"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"ستانلى","city_name_en":"Stanley"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"سموحة","city_name_en":"Smouha"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"سيدى بشر","city_name_en":"Sidi Bishr"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"شدس","city_name_en":"Shads"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"غيط العنب","city_name_en":"Gheet Alenab"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"فلمينج","city_name_en":"Fleming"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"فيكتوريا","city_name_en":"Victoria"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"كامب شيزار","city_name_en":"Camp Shizar"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"كرموز","city_name_en":"Karmooz"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"محطة الرمل","city_name_en":"Mahta Alraml"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"مينا البصل","city_name_en":"Mina El-Basal"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"العصافرة","city_name_en":"Asafra"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"العجمي","city_name_en":"Agamy"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"بكوس","city_name_en":"Bakos"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"بولكلي","city_name_en":"Boulkly"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"كليوباترا","city_name_en":"Cleopatra"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"جليم","city_name_en":"Glim"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المعمورة","city_name_en":"Al Mamurah"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المندرة","city_name_en":"Al Mandara"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"محرم بك","city_name_en":"Moharam Bek"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الشاطبي","city_name_en":"Elshatby"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"سيدي جابر","city_name_en":"Sidi Gaber"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الساحل الشمالي","city_name_en":"North Coast\/sahel"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الحضرة","city_name_en":"Alhadra"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"العطارين","city_name_en":"Alattarin"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"سيدي كرير","city_name_en":"Sidi Kerir"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"الجمرك","city_name_en":"Elgomrok"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"المكس","city_name_en":"Al Max"},
    {"governorates_of_Egypt_id":"3","city_name_ar":"مارينا","city_name_en":"Marina"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"المنصورة","city_name_en":"Mansoura"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"طلخا","city_name_en":"Talkha"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"ميت غمر","city_name_en":"Mitt Ghamr"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"دكرنس","city_name_en":"Dekernes"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"أجا","city_name_en":"Aga"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"منية النصر","city_name_en":"Menia El Nasr"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"السنبلاوين","city_name_en":"Sinbillawin"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"الكردي","city_name_en":"El Kurdi"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"بني عبيد","city_name_en":"Bani Ubaid"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"المنزلة","city_name_en":"Al Manzala"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"تمي الأمديد","city_name_en":"tami al'amdid"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"الجمالية","city_name_en":"aljamalia"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"شربين","city_name_en":"Sherbin"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"المطرية","city_name_en":"Mataria"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"بلقاس","city_name_en":"Belqas"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"ميت سلسيل","city_name_en":"Meet Salsil"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"جمصة","city_name_en":"Gamasa"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"محلة دمنة","city_name_en":"Mahalat Damana"},
    {"governorates_of_Egypt_id":"4","city_name_ar":"نبروه","city_name_en":"Nabroh"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"الغردقة","city_name_en":"Hurghada"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"رأس غارب","city_name_en":"Ras Ghareb"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"سفاجا","city_name_en":"Safaga"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"القصير","city_name_en":"El Qusiar"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"مرسى علم","city_name_en":"Marsa Alam"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"الشلاتين","city_name_en":"Shalatin"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"حلايب","city_name_en":"Halaib"},
    {"governorates_of_Egypt_id":"5","city_name_ar":"الدهار","city_name_en":"Aldahar"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"دمنهور","city_name_en":"Damanhour"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"كفر الدوار","city_name_en":"Kafr El Dawar"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"رشيد","city_name_en":"Rashid"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"إدكو","city_name_en":"Edco"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"أبو المطامير","city_name_en":"Abu al-Matamir"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"أبو حمص","city_name_en":"Abu Homs"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"الدلنجات","city_name_en":"Delengat"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"المحمودية","city_name_en":"Mahmoudiyah"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"الرحمانية","city_name_en":"Rahmaniyah"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"إيتاي البارود","city_name_en":"Itai Baroud"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"حوش عيسى","city_name_en":"Housh Eissa"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"شبراخيت","city_name_en":"Shubrakhit"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"كوم حمادة","city_name_en":"Kom Hamada"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"بدر","city_name_en":"Badr"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"وادي النطرون","city_name_en":"Wadi Natrun"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"النوبارية الجديدة","city_name_en":"New Nubaria"},
    {"governorates_of_Egypt_id":"6","city_name_ar":"النوبارية","city_name_en":"Alnoubareya"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"الفيوم","city_name_en":"Fayoum"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"الفيوم الجديدة","city_name_en":"Fayoum El Gedida"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"طامية","city_name_en":"Tamiya"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"سنورس","city_name_en":"Snores"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"إطسا","city_name_en":"Etsa"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"إبشواي","city_name_en":"Epschway"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"يوسف الصديق","city_name_en":"Yusuf El Sediaq"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"الحادقة","city_name_en":"Hadqa"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"اطسا","city_name_en":"Atsa"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"الجامعة","city_name_en":"Algamaa"},
    {"governorates_of_Egypt_id":"7","city_name_ar":"السيالة","city_name_en":"Sayala"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"طنطا","city_name_en":"Tanta"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"المحلة الكبرى","city_name_en":"Al Mahalla Al Kobra"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"كفر الزيات","city_name_en":"Kafr El Zayat"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"زفتى","city_name_en":"Zefta"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"السنطة","city_name_en":"El Santa"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"قطور","city_name_en":"Qutour"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"بسيون","city_name_en":"Basion"},
    {"governorates_of_Egypt_id":"8","city_name_ar":"سمنود","city_name_en":"Samannoud"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"الإسماعيلية","city_name_en":"Ismailia"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"فايد","city_name_en":"Fayed"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"القنطرة شرق","city_name_en":"Qantara Sharq"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"القنطرة غرب","city_name_en":"Qantara Gharb"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"التل الكبير","city_name_en":"El Tal El Kabier"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"أبو صوير","city_name_en":"Abu Sawir"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"القصاصين الجديدة","city_name_en":"Kasasien El Gedida"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"نفيشة","city_name_en":"Nefesha"},
    {"governorates_of_Egypt_id":"9","city_name_ar":"الشيخ زايد","city_name_en":"Sheikh Zayed"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"شبين الكوم","city_name_en":"Shbeen El Koom"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"مدينة السادات","city_name_en":"Sadat City"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"منوف","city_name_en":"Menouf"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"سرس الليان","city_name_en":"Sars El-Layan"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"أشمون","city_name_en":"Ashmon"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"الباجور","city_name_en":"Al Bagor"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"قويسنا","city_name_en":"Quesna"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"بركة السبع","city_name_en":"Berkat El Saba"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"تلا","city_name_en":"Tala"},
    {"governorates_of_Egypt_id":"10","city_name_ar":"الشهداء","city_name_en":"Al Shohada"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"المنيا","city_name_en":"Minya"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"المنيا الجديدة","city_name_en":"Minya El Gedida"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"العدوة","city_name_en":"El Adwa"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"مغاغة","city_name_en":"Magagha"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"بني مزار","city_name_en":"Bani Mazar"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"مطاي","city_name_en":"Mattay"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"سمالوط","city_name_en":"Samalut"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"المدينة الفكرية","city_name_en":"Madinat El Fekria"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"ملوي","city_name_en":"Meloy"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"دير مواس","city_name_en":"Deir Mawas"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"ابو قرقاص","city_name_en":"Abu Qurqas"},
    {"governorates_of_Egypt_id":"11","city_name_ar":"ارض سلطان","city_name_en":"Ard Sultan"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"بنها","city_name_en":"Banha"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"قليوب","city_name_en":"Qalyub"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"شبرا الخيمة","city_name_en":"Shubra Al Khaimah"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"القناطر الخيرية","city_name_en":"Al Qanater Charity"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"الخانكة","city_name_en":"Khanka"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"كفر شكر","city_name_en":"Kafr Shukr"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"طوخ","city_name_en":"Tukh"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"قها","city_name_en":"Qaha"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"العبور","city_name_en":"Obour"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"الخصوص","city_name_en":"Khosous"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"شبين القناطر","city_name_en":"Shibin Al Qanater"},
    {"governorates_of_Egypt_id":"12","city_name_ar":"مسطرد","city_name_en":"Mostorod"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"الخارجة","city_name_en":"El Kharga"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"باريس","city_name_en":"Paris"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"موط","city_name_en":"Mout"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"الفرافرة","city_name_en":"Farafra"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"بلاط","city_name_en":"Balat"},
    {"governorates_of_Egypt_id":"13","city_name_ar":"الداخلة","city_name_en":"Dakhla"},
    {"governorates_of_Egypt_id":"14","city_name_ar":"السويس","city_name_en":"Suez"},
    {"governorates_of_Egypt_id":"14","city_name_ar":"الجناين","city_name_en":"Alganayen"},
    {"governorates_of_Egypt_id":"14","city_name_ar":"عتاقة","city_name_en":"Ataqah"},
    {"governorates_of_Egypt_id":"14","city_name_ar":"العين السخنة","city_name_en":"Ain Sokhna"},
    {"governorates_of_Egypt_id":"14","city_name_ar":"فيصل","city_name_en":"Faysal"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"أسوان","city_name_en":"Aswan"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"أسوان الجديدة","city_name_en":"Aswan El Gedida"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"دراو","city_name_en":"Drau"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"كوم أمبو","city_name_en":"Kom Ombo"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"نصر النوبة","city_name_en":"Nasr Al Nuba"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"كلابشة","city_name_en":"Kalabsha"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"إدفو","city_name_en":"Edfu"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"الرديسية","city_name_en":"Al-Radisiyah"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"البصيلية","city_name_en":"Al Basilia"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"السباعية","city_name_en":"Al Sibaeia"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"ابوسمبل السياحية","city_name_en":"Abo Simbl Al Siyahia"},
    {"governorates_of_Egypt_id":"15","city_name_ar":"مرسى علم","city_name_en":"Marsa Alam"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"أسيوط","city_name_en":"Assiut"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"أسيوط الجديدة","city_name_en":"Assiut El Gedida"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"ديروط","city_name_en":"Dayrout"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"منفلوط","city_name_en":"Manfalut"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"القوصية","city_name_en":"Qusiya"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"أبنوب","city_name_en":"Abnoub"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"أبو تيج","city_name_en":"Abu Tig"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"الغنايم","city_name_en":"El Ghanaim"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"ساحل سليم","city_name_en":"Sahel Selim"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"البداري","city_name_en":"El Badari"},
    {"governorates_of_Egypt_id":"16","city_name_ar":"صدفا","city_name_en":"Sidfa"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"بني سويف","city_name_en":"Bani Sweif"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"بني سويف الجديدة","city_name_en":"Beni Suef El Gedida"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"الواسطى","city_name_en":"Al Wasta"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"ناصر","city_name_en":"Naser"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"إهناسيا","city_name_en":"Ehnasia"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"ببا","city_name_en":"beba"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"الفشن","city_name_en":"Fashn"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"سمسطا","city_name_en":"Somasta"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"الاباصيرى","city_name_en":"Alabbaseri"},
    {"governorates_of_Egypt_id":"17","city_name_ar":"مقبل","city_name_en":"Mokbel"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"بورسعيد","city_name_en":"PorSaid"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"بورفؤاد","city_name_en":"Port Fouad"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"العرب","city_name_en":"Alarab"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"حى الزهور","city_name_en":"Zohour"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"حى الشرق","city_name_en":"Alsharq"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"حى الضواحى","city_name_en":"Aldawahi"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"حى المناخ","city_name_en":"Almanakh"},
    {"governorates_of_Egypt_id":"18","city_name_ar":"حى مبارك","city_name_en":"Mubarak"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"دمياط","city_name_en":"Damietta"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"دمياط الجديدة","city_name_en":"New Damietta"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"رأس البر","city_name_en":"Ras El Bar"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"فارسكور","city_name_en":"Faraskour"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"الزرقا","city_name_en":"Zarqa"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"السرو","city_name_en":"alsaru"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"الروضة","city_name_en":"alruwda"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"كفر البطيخ","city_name_en":"Kafr El-Batikh"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"عزبة البرج","city_name_en":"Azbet Al Burg"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"ميت أبو غالب","city_name_en":"Meet Abou Ghalib"},
    {"governorates_of_Egypt_id":"19","city_name_ar":"كفر سعد","city_name_en":"Kafr Saad"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"الزقازيق","city_name_en":"Zagazig"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"العاشر من رمضان","city_name_en":"Al Ashr Men Ramadan"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"منيا القمح","city_name_en":"Minya Al Qamh"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"بلبيس","city_name_en":"Belbeis"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"مشتول السوق","city_name_en":"Mashtoul El Souq"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"القنايات","city_name_en":"Qenaiat"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"أبو حماد","city_name_en":"Abu Hammad"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"القرين","city_name_en":"El Qurain"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"ههيا","city_name_en":"Hehia"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"أبو كبير","city_name_en":"Abu Kabir"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"فاقوس","city_name_en":"Faccus"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"الصالحية الجديدة","city_name_en":"El Salihia El Gedida"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"الإبراهيمية","city_name_en":"Al Ibrahimiyah"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"ديرب نجم","city_name_en":"Deirb Negm"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"كفر صقر","city_name_en":"Kafr Saqr"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"أولاد صقر","city_name_en":"Awlad Saqr"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"الحسينية","city_name_en":"Husseiniya"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"صان الحجر القبلية","city_name_en":"san alhajar alqablia"},
    {"governorates_of_Egypt_id":"20","city_name_ar":"منشأة أبو عمر","city_name_en":"Manshayat Abu Omar"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"الطور","city_name_en":"Al Toor"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"شرم الشيخ","city_name_en":"Sharm El-Shaikh"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"دهب","city_name_en":"Dahab"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"نويبع","city_name_en":"Nuweiba"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"طابا","city_name_en":"Taba"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"سانت كاترين","city_name_en":"Saint Catherine"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"أبو رديس","city_name_en":"Abu Redis"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"أبو زنيمة","city_name_en":"Abu Zenaima"},
    {"governorates_of_Egypt_id":"21","city_name_ar":"رأس سدر","city_name_en":"Ras Sidr"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"كفر الشيخ","city_name_en":"Kafr El Sheikh"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"وسط البلد كفر الشيخ","city_name_en":"Kafr El Sheikh Downtown"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"دسوق","city_name_en":"Desouq"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"فوه","city_name_en":"Fooh"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"مطوبس","city_name_en":"Metobas"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"برج البرلس","city_name_en":"Burg Al Burullus"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"بلطيم","city_name_en":"Baltim"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"مصيف بلطيم","city_name_en":"Masief Baltim"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"الحامول","city_name_en":"Hamol"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"بيلا","city_name_en":"Bella"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"الرياض","city_name_en":"Riyadh"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"سيدي سالم","city_name_en":"Sidi Salm"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"قلين","city_name_en":"Qellen"},
    {"governorates_of_Egypt_id":"22","city_name_ar":"سيدي غازي","city_name_en":"Sidi Ghazi"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"مرسى مطروح","city_name_en":"Marsa Matrouh"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"الحمام","city_name_en":"El Hamam"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"العلمين","city_name_en":"Alamein"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"الضبعة","city_name_en":"Dabaa"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"النجيلة","city_name_en":"Al-Nagila"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"سيدي براني","city_name_en":"Sidi Brani"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"السلوم","city_name_en":"Salloum"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"سيوة","city_name_en":"Siwa"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"مارينا","city_name_en":"Marina"},
    {"governorates_of_Egypt_id":"23","city_name_ar":"الساحل الشمالى","city_name_en":"North Coast"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"الأقصر","city_name_en":"Luxor"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"الأقصر الجديدة","city_name_en":"New Luxor"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"إسنا","city_name_en":"Esna"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"طيبة الجديدة","city_name_en":"New Tiba"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"الزينية","city_name_en":"Al ziynia"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"البياضية","city_name_en":"Al Bayadieh"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"القرنة","city_name_en":"Al Qarna"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"أرمنت","city_name_en":"Armant"},
    {"governorates_of_Egypt_id":"24","city_name_ar":"الطود","city_name_en":"Al Tud"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"قنا","city_name_en":"Qena"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"قنا الجديدة","city_name_en":"New Qena"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"ابو طشت","city_name_en":"Abu Tesht"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"نجع حمادي","city_name_en":"Nag Hammadi"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"دشنا","city_name_en":"Deshna"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"الوقف","city_name_en":"Alwaqf"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"قفط","city_name_en":"Qaft"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"نقادة","city_name_en":"Naqada"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"فرشوط","city_name_en":"Farshout"},
    {"governorates_of_Egypt_id":"25","city_name_ar":"قوص","city_name_en":"Quos"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"العريش","city_name_en":"Arish"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"الشيخ زويد","city_name_en":"Sheikh Zowaid"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"نخل","city_name_en":"Nakhl"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"رفح","city_name_en":"Rafah"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"بئر العبد","city_name_en":"Bir al-Abed"},
    {"governorates_of_Egypt_id":"26","city_name_ar":"الحسنة","city_name_en":"Al Hasana"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"سوهاج","city_name_en":"Sohag"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"سوهاج الجديدة","city_name_en":"Sohag El Gedida"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"أخميم","city_name_en":"Akhmeem"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"أخميم الجديدة","city_name_en":"Akhmim El Gedida"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"البلينا","city_name_en":"Albalina"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"المراغة","city_name_en":"El Maragha"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"المنشأة","city_name_en":"almunsha'a"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"دار السلام","city_name_en":"Dar AISalaam"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"جرجا","city_name_en":"Gerga"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"جهينة الغربية","city_name_en":"Jahina Al Gharbia"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"ساقلته","city_name_en":"Saqilatuh"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"طما","city_name_en":"Tama"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"طهطا","city_name_en":"Tahta"},
    {"governorates_of_Egypt_id":"27","city_name_ar":"الكوثر","city_name_en":"Alkawthar"}
  ];