name: teacher_care
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animate_do: ^2.0.0
  animated_splash_screen: ^1.1.0
  avatar_glow: ^2.0.1
  bloc: ^7.0.0
  cached_network_image: ^3.0.0
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  device_preview: ^0.7.3
  dio: ^4.0.0
  dropdown_plus: ^0.0.8
  flutter_bloc: ^7.0.1
  flutter_blurhash: ^0.6.0
  flutter_onboard: ^1.0.0
  folding_menu: ^1.0.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  image_picker: ^0.8.0+3
  jitsi_meet: ^4.0.0
  loading_indicator: ^2.1.1
  octo_image: ^1.0.0+1
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_view: ^0.11.1
  provider: ^5.0.0
  responsive_framework: ^0.1.4
  shared_preferences: ^2.0.6
  sizer: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  snapping_sheet: ^3.1.0
  sqflite: ^2.0.0+3
  widget_circular_animator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/profile_bio/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
